/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as MoreStatisticsRouteImport } from './routes/more-statistics'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeeNameRouteImport } from './routes/employee.$name'

const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreStatisticsRoute = MoreStatisticsRouteImport.update({
  id: '/more-statistics',
  path: '/more-statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeNameRoute = EmployeeNameRouteImport.update({
  id: '/employee/$name',
  path: '/employee/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/more-statistics': typeof MoreStatisticsRoute
  '/recommendations': typeof RecommendationsRoute
  '/employee/$name': typeof EmployeeNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/more-statistics': typeof MoreStatisticsRoute
  '/recommendations': typeof RecommendationsRoute
  '/employee/$name': typeof EmployeeNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/more-statistics': typeof MoreStatisticsRoute
  '/recommendations': typeof RecommendationsRoute
  '/employee/$name': typeof EmployeeNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/more-statistics'
    | '/recommendations'
    | '/employee/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/more-statistics'
    | '/recommendations'
    | '/employee/$name'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/more-statistics'
    | '/recommendations'
    | '/employee/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MoreStatisticsRoute: typeof MoreStatisticsRoute
  RecommendationsRoute: typeof RecommendationsRoute
  EmployeeNameRoute: typeof EmployeeNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more-statistics': {
      id: '/more-statistics'
      path: '/more-statistics'
      fullPath: '/more-statistics'
      preLoaderRoute: typeof MoreStatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/$name': {
      id: '/employee/$name'
      path: '/employee/$name'
      fullPath: '/employee/$name'
      preLoaderRoute: typeof EmployeeNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MoreStatisticsRoute: MoreStatisticsRoute,
  RecommendationsRoute: RecommendationsRoute,
  EmployeeNameRoute: EmployeeNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
